Servidor API REST:
(ve_...) D:\practian o XXX\ioteca\ioteca_service>pip install -r requirements.txt

(ve_...) D:\practian o XXX\ioteca\ioteca_service>manage.py runserver 9000
Performing system checks...

System check identified no issues (0 silenced).
May 04, 2016 - 12:50:12
Django version 1.9.5, using settings 'ioteca_main.settings'
Starting development server at http://127.0.0.1:9000/
Quit the server with CTRL-BREAK.




Client web:
D:\practian o XXX\ioteca>npm install

D:\practian o XXX\ioteca\auth_web>bower install
D:\practian o XXX\ioteca\ioteca_web>bower install

D:\practian o XXX\ioteca>gulp serve
[09:22:36] Using gulpfile D:\practian o XXX\ioteca\gulpfile.js
[09:22:36] Starting 'serve'...
[09:22:36] Finished 'serve' after 93 ms
[09:22:36] Server started http://localhost:9001

Si cambia modificar las urls en:
.\ioteca\auth_web\app\config.js

.\ioteca\ioteca_web\app\config.js
y
.\ioteca\ioteca_web\ioteca_web_apps\auths\config.js
y en los que se usa URLs


// USER : admin
// PASSWORD : 12345


Backup database
-------------------
(ve_...) D:\practian o XXX\ioteca\ioteca_service>manage.py dumpdata > fixtures/ini_data.json --exclude=corsheaders


Load o restore database
-------------------
See in the settings.py setting for FIXTURE_DIRS
   (ve_...) ...>manage.py loaddata ini_data
else 
 	(ve_...) ...>manage.py loaddata fixtures\ini_data.json


Clean database
-------------------
Run the following command:

    (ve_...) ..._api>manage.py flush
    
    and exec in admin db

	  >delete from django_content_type;

	  >delete from auth_permission;



Django==1.9.6
django-braces==1.8.1
django-cors-headers==1.1.0
django-oauth-toolkit==0.10.0
djangorestframework==3.3.3
docutils==0.12
oauthlib==1.0.3
Pillow==3.2.0
six==1.10.0